from enum import Enum

class State(Enum):
    BOOTING = "BOOTING"
    CONNECTING = "CONNECTING"
    CONNECTED = "CONNECTED"
    LISTENING = "LISTENING"
    WAKE_DETECTED = "WAKE_DETECTED"
    STREAMING_AUDIO = "STREAMING_AUDIO"
    WAITING_RESPONSE = "WAITING_RESPONSE"
    PLAYING_TTS = "PLAYING_TTS"
    ERROR = "ERROR"
    RECONNECTING = "RECONNECTING"

# Protocol Messages
MSG_TYPE_TTS_END = "tts_end"
MSG_TYPE_START_STREAM = "START_STREAM"
MSG_TYPE_STOP_STREAM = "STOP_STREAM"
